server:
  port: 443
  ssl:
    key-alias: guxiangfly.cn
    key-store-type: JKS
    key-store: classpath:guxiangfly.cn.jks
    key-store-password: 45lgrs8gokejt0


spring:
  datasource:
     url: jdbc:mysql://47.96.173.94:3306/runningcoin?useUnicode=yes&amp;characterEncoding=UTF-8&amp;useSSL=false
     username: root
     password: qwert6
     driver-class-name: com.mysql.jdbc.Driver
