server:
  port: 443
  ssl:
    key-alias: guxiangfly.cn
    key-store-type: JKS
    key-store: classpath:guxiangfly.cn.jks
    key-store-password: 45lgrs8gokejt0
spring:
  datasource:
     url: jdbc:mysql://47.96.173.94:3306/runningcoin_QA?useUnicode=yes&useSSL=false
     username: root
     password: qwert6
     driver-class-name: com.mysql.jdbc.Driver
  mail:
    host: smtp.qq.com
    username: 964999133@qq.com
    password: plmksuixpkdmbcag
    addressesEmail: xianggu@ebay.com,bshen@ebay.com
    properties.mail.smtp.auth: true
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
wechat:
  appid: wx5fac28aeaaaa5a59
  secret: 3a6a7edad78faf5fa48d64a0911b6b87