server:
  port: 2443
  # 改为已经改为Nginx部署
  servlet:
    context-path: /prod/
  #ssl:
  #  key-alias: guxiangfly.cn
  #  key-store-type: JKS
  #  key-store: classpath:guxiangfly.cn.jks
  #  key-store-password: 45lgrs8gokejt0
spring:
  datasource:
     url: jdbc:mysql://47.96.173.94:3306/runningcoin?useUnicode=yes&useSSL=false
     username: root
     password: qwert6
     driver-class-name: com.mysql.jdbc.Driver
  mail:
    host: smtp.qq.com
    username: 964999133@qq.com
    password: plmksuixpkdmbcag
  # addressesEmail: xianggu@ebay.com,bshen@ebay.com
    addressesEmail: xianggu@ebay.com
    properties.mail.smtp.auth: true
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
wechat:
  appid: wx8220102dd8c2c642
  secret: c278c7b91d6d6aca16016297812d4972